// Generated by delombok at Fri May 17 11:49:19 CEST 2013
/**
 * Copyright (C) 2010-2013 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX. If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx;
/**
 * A channel entry returned from /LIST command
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */

public class ChannelListEntry {
	protected final String name;
	protected final int users;
	protected final String topic;
	
	public ChannelListEntry(String name, int users, String topic) {
		
		this.name = name;
		this.users = users;
		this.topic = topic;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}
	
	@java.lang.SuppressWarnings("all")
	public int getUsers() {
		return this.users;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getTopic() {
		return this.topic;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ChannelListEntry)) return false;
		final ChannelListEntry other = (ChannelListEntry)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		if (this.getUsers() != other.getUsers()) return false;
		final java.lang.Object this$topic = this.getTopic();
		final java.lang.Object other$topic = other.getTopic();
		if (this$topic == null ? other$topic != null : !this$topic.equals(other$topic)) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof ChannelListEntry;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 0 : $name.hashCode());
		result = result * PRIME + this.getUsers();
		final java.lang.Object $topic = this.getTopic();
		result = result * PRIME + ($topic == null ? 0 : $topic.hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "ChannelListEntry(name=" + this.getName() + ", users=" + this.getUsers() + ", topic=" + this.getTopic() + ")";
	}
}