// Generated by delombok at Thu Oct 04 13:11:43 CEST 2012
/**
 * Copyright (C) 2010-2011 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx;
/**
 * A channel entry returned from /LIST command
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */

public class ChannelListEntry {
	protected final String name;
	protected final int users;
	protected final String topic;
	
	public ChannelListEntry(String name, int users, String topic) {
		this.name = name;
		this.users = users;
		this.topic = topic;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}
	
	@java.lang.SuppressWarnings("all")
	public int getUsers() {
		return this.users;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getTopic() {
		return this.topic;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof ChannelListEntry)) return false;
		final ChannelListEntry other = (ChannelListEntry)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (this.getName() == null ? other.getName() != null : !this.getName().equals((java.lang.Object)other.getName())) return false;
		if (this.getUsers() != other.getUsers()) return false;
		if (this.getTopic() == null ? other.getTopic() != null : !this.getTopic().equals((java.lang.Object)other.getTopic())) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof ChannelListEntry;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + (this.getName() == null ? 0 : this.getName().hashCode());
		result = result * PRIME + this.getUsers();
		result = result * PRIME + (this.getTopic() == null ? 0 : this.getTopic().hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "ChannelListEntry(name=" + this.getName() + ", users=" + this.getUsers() + ", topic=" + this.getTopic() + ")";
	}
}