// Generated by delombok at Fri May 17 11:49:19 CEST 2013
/**
 * Copyright (C) 2010-2013 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX. If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx;

import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.net.InetAddress;
import java.nio.charset.Charset;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.net.SocketFactory;
import org.pircbotx.exception.IrcException;
import org.pircbotx.exception.NickAlreadyInUseException;
import org.pircbotx.hooks.managers.ListenerManager;
/**
 * Manager that provides an easy way to create bots on many different servers
 * with the same or close to the same information. All important setup methods
 * have been mirrored here. For documentation, see their equivalent PircBotX
 * methods.
 * <p>
 * <b>Note:</b> Setting any value after connectAll() is invoked will NOT update
 * all existing bots. You will need to loop over the bots and call the set methods
 * manually
 * <p/>
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */

@SuppressWarnings({"unchecked", "rawtypes"})
public class MultiBotManager {
	protected final Set<BotEntry> bots = new HashSet();
	protected final HeufyBot dummyBot;
	protected ListenerManager listenerManager;
	protected String name;
	protected boolean verbose;
	protected int socketTimeout;
	protected long messageDelay;
	protected String login;
	protected boolean autoNickChange;
	protected Charset encoding;
	protected InetAddress dcciNetAddress;
	protected List<Integer> dccports;
	/**
	 * Setup MultiBotManager with all bots being called the specified name
	 * @param name The name that all bots will have by default
	 */
	public MultiBotManager(final String givenName) {
		this(new HeufyBot(false){
			
			{
				setName(givenName);
			}
		});
	}
	/**
	 * Setup MultiBotManager by cloning ALL of the settings from the specified
	 * bot
	 * @param dummyBot The bot to clone the settings from
	 */
	public MultiBotManager(HeufyBot dummyBot) {
		
		//Mirror the values 
		this.dummyBot = dummyBot;
		name = dummyBot.getName();
		listenerManager = dummyBot.getListenerManager();
		verbose = dummyBot.isVerbose();
		socketTimeout = dummyBot.getSocketTimeout();
		messageDelay = dummyBot.getMessageDelay();
		login = dummyBot.getLogin();
		autoNickChange = dummyBot.isAutoNickChange();
		encoding = dummyBot.getEncoding();
	}
	/**
	 * Create a bot using the specified hostname, 6667 for port, and no password or socketfactory
	 * @param hostname The hostname of the server to connect to.
	 */
	public BotBuilder createBot(String hostname) {
		return createBot(hostname, 6667, null, null);
	}
	/**
	 * Attempt to connect to the specified IRC server and port number.
	 * The onConnect method is called upon success.
	 *
	 * @param hostname The hostname of the server to connect to.
	 * @param port The port number to connect to on the server.
	 */
	public BotBuilder createBot(String hostname, int port) throws IOException, IrcException, NickAlreadyInUseException {
		return createBot(hostname, port, null, null);
	}
	/**
	 * Create a bot using the specified hostname, port and socketfactory with no password
	 * @param hostname The hostname of the server to connect to.
	 * @param port The port number to connect to on the server.
	 * @param socketFactory The factory to use for creating sockets, including secure sockets
	 */
	public BotBuilder createBot(String hostname, int port, SocketFactory socketFactory) {
		return createBot(hostname, port, null, socketFactory);
	}
	/**
	 * Create a bot using the specified hostname, port, password, and socketfactory
	 * @param hostname The hostname of the server to connect to.
	 * @param port The port number to connect to on the server.
	 * @param password The password to use to join the server.
	 * @param socketFactory The factory to use for creating sockets, including secure sockets
	 */
	public BotBuilder createBot(String hostname, int port, String password, SocketFactory socketFactory) {
		//Create bot with all of the global settings
		HeufyBot bot = new HeufyBot(false);
		bot.setListenerManager(listenerManager);
		bot.setName(name);
		bot.setVerbose(verbose);
		bot.setSocketTimeout(socketTimeout);
		bot.setMessageDelay(messageDelay);
		bot.setLogin(login);
		bot.setAutoNickChange(autoNickChange);
		bot.setEncoding(encoding);
		//Add to bot set
		BotBuilder builder = new BotBuilder(bot);
		bots.add(new BotEntry(bot, hostname, port, password, socketFactory, builder));
		return builder;
	}
	/**
	 * Connect all bots to their respective hosts and channels
	 * @throws IOException if it was not possible to connect to the server.
	 * @throws IrcException if the server would not let us join it.
	 * @throws NickAlreadyInUseException if our nick is already in use on the server.
	 */
	public void connectAll() throws IOException, IrcException, NickAlreadyInUseException {
		for (BotEntry curEntry : bots) {
			HeufyBot bot = curEntry.getBot();
			bot.connect(curEntry.getHostname(), curEntry.getPort(), curEntry.getPassword(), curEntry.getSocketFactory());
			//Join channels
			for (Map.Entry<String, String> curChannel : curEntry.getBuilder().getChannels().entrySet()) bot.joinChannel(curChannel.getKey(), curChannel.getValue());
		}
	}
	/**
	 * Disconnect all bots from their respective severs cleanly.
	 */
	public void disconnectAll() {
		for (BotEntry curEntry : bots) {
			HeufyBot bot = curEntry.getBot();
			if (bot.isConnected()) bot.disconnect();
		}
	}
	/**
	 * Get all the bots that this MultiBotManager is managing. Do not save this
	 * anywhere as it will be out of date when a new bot is created
	 * @return An <i>unmodifiable</i> Set of bots that are being managed
	 */
	public Set<HeufyBot> getBots() {
		Set<HeufyBot> actualBots = new HashSet();
		for (BotEntry curEntry : bots) actualBots.add(curEntry.getBot());
		return Collections.unmodifiableSet(actualBots);
	}
	
	public void setEncoding(String encoding) throws UnsupportedEncodingException {
		//Test if exception is thrown when setting encoding
		dummyBot.setEncoding(encoding);
		//Good, set value
		this.encoding = dummyBot.getEncoding();
	}
	
	protected static class BotEntry {
		protected final HeufyBot bot;
		protected final String hostname;
		protected final int port;
		protected final String password;
		protected final SocketFactory socketFactory;
		protected final BotBuilder builder;
		
		@java.beans.ConstructorProperties({"bot", "hostname", "port", "password", "socketFactory", "builder"})
		@java.lang.SuppressWarnings("all")
		public BotEntry(final HeufyBot bot, final String hostname, final int port, final String password, final SocketFactory socketFactory, final BotBuilder builder) {
			
			this.bot = bot;
			this.hostname = hostname;
			this.port = port;
			this.password = password;
			this.socketFactory = socketFactory;
			this.builder = builder;
		}
		
		@java.lang.SuppressWarnings("all")
		public HeufyBot getBot() {
			return this.bot;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getHostname() {
			return this.hostname;
		}
		
		@java.lang.SuppressWarnings("all")
		public int getPort() {
			return this.port;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getPassword() {
			return this.password;
		}
		
		@java.lang.SuppressWarnings("all")
		public SocketFactory getSocketFactory() {
			return this.socketFactory;
		}
		
		@java.lang.SuppressWarnings("all")
		public BotBuilder getBuilder() {
			return this.builder;
		}
		
		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public boolean equals(final java.lang.Object o) {
			if (o == this) return true;
			if (!(o instanceof MultiBotManager.BotEntry)) return false;
			final BotEntry other = (BotEntry)o;
			if (!other.canEqual((java.lang.Object)this)) return false;
			final java.lang.Object this$bot = this.getBot();
			final java.lang.Object other$bot = other.getBot();
			if (this$bot == null ? other$bot != null : !this$bot.equals(other$bot)) return false;
			final java.lang.Object this$hostname = this.getHostname();
			final java.lang.Object other$hostname = other.getHostname();
			if (this$hostname == null ? other$hostname != null : !this$hostname.equals(other$hostname)) return false;
			if (this.getPort() != other.getPort()) return false;
			final java.lang.Object this$password = this.getPassword();
			final java.lang.Object other$password = other.getPassword();
			if (this$password == null ? other$password != null : !this$password.equals(other$password)) return false;
			final java.lang.Object this$socketFactory = this.getSocketFactory();
			final java.lang.Object other$socketFactory = other.getSocketFactory();
			if (this$socketFactory == null ? other$socketFactory != null : !this$socketFactory.equals(other$socketFactory)) return false;
			final java.lang.Object this$builder = this.getBuilder();
			final java.lang.Object other$builder = other.getBuilder();
			if (this$builder == null ? other$builder != null : !this$builder.equals(other$builder)) return false;
			return true;
		}
		
		@java.lang.SuppressWarnings("all")
		public boolean canEqual(final java.lang.Object other) {
			return other instanceof MultiBotManager.BotEntry;
		}
		
		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public int hashCode() {
			final int PRIME = 31;
			int result = 1;
			final java.lang.Object $bot = this.getBot();
			result = result * PRIME + ($bot == null ? 0 : $bot.hashCode());
			final java.lang.Object $hostname = this.getHostname();
			result = result * PRIME + ($hostname == null ? 0 : $hostname.hashCode());
			result = result * PRIME + this.getPort();
			final java.lang.Object $password = this.getPassword();
			result = result * PRIME + ($password == null ? 0 : $password.hashCode());
			final java.lang.Object $socketFactory = this.getSocketFactory();
			result = result * PRIME + ($socketFactory == null ? 0 : $socketFactory.hashCode());
			final java.lang.Object $builder = this.getBuilder();
			result = result * PRIME + ($builder == null ? 0 : $builder.hashCode());
			return result;
		}
		
		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "MultiBotManager.BotEntry(bot=" + this.getBot() + ", hostname=" + this.getHostname() + ", port=" + this.getPort() + ", password=" + this.getPassword() + ", socketFactory=" + this.getSocketFactory() + ", builder=" + this.getBuilder() + ")";
		}
	}
	
	public static class BotBuilder {
		protected final HeufyBot bot;
		protected Map<String, String> channels = new HashMap();
		
		public BotBuilder addChannel(String channelName) {
			channels.put(channelName, "");
			return this;
		}
		
		public BotBuilder addChannel(String channelName, String key) {
			channels.put(channelName, key);
			return this;
		}
		
		@java.beans.ConstructorProperties({"bot"})
		@java.lang.SuppressWarnings("all")
		public BotBuilder(final HeufyBot bot) {
			
			this.bot = bot;
		}
		
		@java.lang.SuppressWarnings("all")
		public HeufyBot getBot() {
			return this.bot;
		}
		
		@java.lang.SuppressWarnings("all")
		protected Map<String, String> getChannels() {
			return this.channels;
		}
	}
	
	@java.lang.SuppressWarnings("all")
	public ListenerManager getListenerManager() {
		return this.listenerManager;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getName() {
		return this.name;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean isVerbose() {
		return this.verbose;
	}
	
	@java.lang.SuppressWarnings("all")
	public int getSocketTimeout() {
		return this.socketTimeout;
	}
	
	@java.lang.SuppressWarnings("all")
	public long getMessageDelay() {
		return this.messageDelay;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getLogin() {
		return this.login;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean isAutoNickChange() {
		return this.autoNickChange;
	}
	
	@java.lang.SuppressWarnings("all")
	public Charset getEncoding() {
		return this.encoding;
	}
	
	@java.lang.SuppressWarnings("all")
	public InetAddress getDcciNetAddress() {
		return this.dcciNetAddress;
	}
	
	@java.lang.SuppressWarnings("all")
	public List<Integer> getDccports() {
		return this.dccports;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setListenerManager(final ListenerManager listenerManager) {
		this.listenerManager = listenerManager;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setName(final String name) {
		this.name = name;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setVerbose(final boolean verbose) {
		this.verbose = verbose;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setSocketTimeout(final int socketTimeout) {
		this.socketTimeout = socketTimeout;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setMessageDelay(final long messageDelay) {
		this.messageDelay = messageDelay;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setLogin(final String login) {
		this.login = login;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setAutoNickChange(final boolean autoNickChange) {
		this.autoNickChange = autoNickChange;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setDcciNetAddress(final InetAddress dcciNetAddress) {
		this.dcciNetAddress = dcciNetAddress;
	}
	
	@java.lang.SuppressWarnings("all")
	public void setDccports(final List<Integer> dccports) {
		this.dccports = dccports;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof MultiBotManager)) return false;
		final MultiBotManager other = (MultiBotManager)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		final java.lang.Object this$bots = this.getBots();
		final java.lang.Object other$bots = other.getBots();
		if (this$bots == null ? other$bots != null : !this$bots.equals(other$bots)) return false;
		final java.lang.Object this$dummyBot = this.dummyBot;
		final java.lang.Object other$dummyBot = other.dummyBot;
		if (this$dummyBot == null ? other$dummyBot != null : !this$dummyBot.equals(other$dummyBot)) return false;
		final java.lang.Object this$listenerManager = this.getListenerManager();
		final java.lang.Object other$listenerManager = other.getListenerManager();
		if (this$listenerManager == null ? other$listenerManager != null : !this$listenerManager.equals(other$listenerManager)) return false;
		final java.lang.Object this$name = this.getName();
		final java.lang.Object other$name = other.getName();
		if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
		if (this.isVerbose() != other.isVerbose()) return false;
		if (this.getSocketTimeout() != other.getSocketTimeout()) return false;
		if (this.getMessageDelay() != other.getMessageDelay()) return false;
		final java.lang.Object this$login = this.getLogin();
		final java.lang.Object other$login = other.getLogin();
		if (this$login == null ? other$login != null : !this$login.equals(other$login)) return false;
		if (this.isAutoNickChange() != other.isAutoNickChange()) return false;
		final java.lang.Object this$encoding = this.getEncoding();
		final java.lang.Object other$encoding = other.getEncoding();
		if (this$encoding == null ? other$encoding != null : !this$encoding.equals(other$encoding)) return false;
		final java.lang.Object this$dcciNetAddress = this.getDcciNetAddress();
		final java.lang.Object other$dcciNetAddress = other.getDcciNetAddress();
		if (this$dcciNetAddress == null ? other$dcciNetAddress != null : !this$dcciNetAddress.equals(other$dcciNetAddress)) return false;
		final java.lang.Object this$dccports = this.getDccports();
		final java.lang.Object other$dccports = other.getDccports();
		if (this$dccports == null ? other$dccports != null : !this$dccports.equals(other$dccports)) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof MultiBotManager;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		final java.lang.Object $bots = this.getBots();
		result = result * PRIME + ($bots == null ? 0 : $bots.hashCode());
		final java.lang.Object $dummyBot = this.dummyBot;
		result = result * PRIME + ($dummyBot == null ? 0 : $dummyBot.hashCode());
		final java.lang.Object $listenerManager = this.getListenerManager();
		result = result * PRIME + ($listenerManager == null ? 0 : $listenerManager.hashCode());
		final java.lang.Object $name = this.getName();
		result = result * PRIME + ($name == null ? 0 : $name.hashCode());
		result = result * PRIME + (this.isVerbose() ? 1231 : 1237);
		result = result * PRIME + this.getSocketTimeout();
		final long $messageDelay = this.getMessageDelay();
		result = result * PRIME + (int)($messageDelay >>> 32 ^ $messageDelay);
		final java.lang.Object $login = this.getLogin();
		result = result * PRIME + ($login == null ? 0 : $login.hashCode());
		result = result * PRIME + (this.isAutoNickChange() ? 1231 : 1237);
		final java.lang.Object $encoding = this.getEncoding();
		result = result * PRIME + ($encoding == null ? 0 : $encoding.hashCode());
		final java.lang.Object $dcciNetAddress = this.getDcciNetAddress();
		result = result * PRIME + ($dcciNetAddress == null ? 0 : $dcciNetAddress.hashCode());
		final java.lang.Object $dccports = this.getDccports();
		result = result * PRIME + ($dccports == null ? 0 : $dccports.hashCode());
		return result;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "MultiBotManager(bots=" + this.getBots() + ", dummyBot=" + this.dummyBot + ", listenerManager=" + this.getListenerManager() + ", name=" + this.getName() + ", verbose=" + this.isVerbose() + ", socketTimeout=" + this.getSocketTimeout() + ", messageDelay=" + this.getMessageDelay() + ", login=" + this.getLogin() + ", autoNickChange=" + this.isAutoNickChange() + ", encoding=" + this.getEncoding() + ", dcciNetAddress=" + this.getDcciNetAddress() + ", dccports=" + this.getDccports() + ")";
	}
}