// Generated by delombok at Thu Oct 04 13:11:43 CEST 2012
/**
 * Copyright (C) 2010-2011 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx.hooks.events;

import org.pircbotx.Channel;
import org.pircbotx.User;
import org.pircbotx.hooks.Event;
import org.pircbotx.HeufyBot;
/**
 * This event is dispatched whenever a user sets the topic, or when
 * we join a new channel and discovers its topic.
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */

public class TopicEvent<T extends HeufyBot> extends Event<T> {
	protected final Channel channel;
	protected final String topic;
	protected final User user;
	protected final boolean changed;
	protected final long date;
	/**
	 * Default constructor to setup object. Timestamp is automatically set
	 * to current time as reported by {@link System#currentTimeMillis() }
	 * @param channel The channel that the topic belongs to.
	 * @param topic The topic for the channel.
	 * @param user The user that set the topic.
	 * @param date When the topic was set (milliseconds since the epoch).
	 * @param changed True if the topic has just been changed, false if
	 *                the topic was already there.
	 */
	public TopicEvent(T bot, Channel channel, String topic, User user, long date, boolean changed) {
		super(bot);
		this.channel = channel;
		this.topic = topic;
		this.user = user;
		this.changed = changed;
		this.date = date;
	}
	/**
	 * Respond with a channel message in <code>user: message</code> format to the
	 * user that set the message
	 * @param response The response to send 
	 */
	@Override
	public void respond(String response) {
		getBot().sendMessage(getChannel(), getUser(), response);
	}
	
	@java.lang.SuppressWarnings("all")
	public Channel getChannel() {
		return this.channel;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getTopic() {
		return this.topic;
	}
	
	@java.lang.SuppressWarnings("all")
	public User getUser() {
		return this.user;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean isChanged() {
		return this.changed;
	}
	
	@java.lang.SuppressWarnings("all")
	public long getDate() {
		return this.date;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "TopicEvent(channel=" + this.getChannel() + ", topic=" + this.getTopic() + ", user=" + this.getUser() + ", changed=" + this.isChanged() + ", date=" + this.getDate() + ")";
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof TopicEvent)) return false;
		final TopicEvent<?> other = (TopicEvent<?>)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		if (this.getChannel() == null ? other.getChannel() != null : !this.getChannel().equals((java.lang.Object)other.getChannel())) return false;
		if (this.getTopic() == null ? other.getTopic() != null : !this.getTopic().equals((java.lang.Object)other.getTopic())) return false;
		if (this.getUser() == null ? other.getUser() != null : !this.getUser().equals((java.lang.Object)other.getUser())) return false;
		if (this.isChanged() != other.isChanged()) return false;
		if (this.getDate() != other.getDate()) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof TopicEvent;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + super.hashCode();
		result = result * PRIME + (this.getChannel() == null ? 0 : this.getChannel().hashCode());
		result = result * PRIME + (this.getTopic() == null ? 0 : this.getTopic().hashCode());
		result = result * PRIME + (this.getUser() == null ? 0 : this.getUser().hashCode());
		result = result * PRIME + (this.isChanged() ? 1231 : 1237);
		result = result * PRIME + (int)(this.getDate() >>> 32 ^ this.getDate());
		return result;
	}
}