// Generated by delombok at Fri May 17 11:49:19 CEST 2013
/**
 * Copyright (C) 2010-2013 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX. If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx.hooks.events;

import org.pircbotx.User;
import org.pircbotx.hooks.Event;
import org.pircbotx.HeufyBot;
/**
 * Called when the mode of a user is set.
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */

public class UserModeEvent<T extends HeufyBot> extends Event<T> {
	protected final User target;
	protected final User source;
	protected final String mode;
	/**
	 * Default constructor to setup object. Timestamp is automatically set
	 * to current time as reported by {@link System#currentTimeMillis() }
	 * @param target The user that the mode operation applies to.
	 * @param source The user that set the mode.
	 * @param mode The mode that has been set.
	 */
	public UserModeEvent(T bot, User target, User source, String mode) {
		super(bot);
		this.target = target;
		this.source = source;
		this.mode = mode;
	}
	/**
	 * Respond with a private message to the source user
	 * @param response The response to send
	 */
	@Override
	public void respond(String response) {
		getBot().sendMessage(getSource(), response);
	}
	
	@java.lang.SuppressWarnings("all")
	public User getTarget() {
		return this.target;
	}
	
	@java.lang.SuppressWarnings("all")
	public User getSource() {
		return this.source;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getMode() {
		return this.mode;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "UserModeEvent(target=" + this.getTarget() + ", source=" + this.getSource() + ", mode=" + this.getMode() + ")";
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof UserModeEvent)) return false;
		final UserModeEvent<?> other = (UserModeEvent<?>)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$target = this.getTarget();
		final java.lang.Object other$target = other.getTarget();
		if (this$target == null ? other$target != null : !this$target.equals(other$target)) return false;
		final java.lang.Object this$source = this.getSource();
		final java.lang.Object other$source = other.getSource();
		if (this$source == null ? other$source != null : !this$source.equals(other$source)) return false;
		final java.lang.Object this$mode = this.getMode();
		final java.lang.Object other$mode = other.getMode();
		if (this$mode == null ? other$mode != null : !this$mode.equals(other$mode)) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof UserModeEvent;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + super.hashCode();
		final java.lang.Object $target = this.getTarget();
		result = result * PRIME + ($target == null ? 0 : $target.hashCode());
		final java.lang.Object $source = this.getSource();
		result = result * PRIME + ($source == null ? 0 : $source.hashCode());
		final java.lang.Object $mode = this.getMode();
		result = result * PRIME + ($mode == null ? 0 : $mode.hashCode());
		return result;
	}
}