// Generated by delombok at Thu Oct 04 13:11:43 CEST 2012
/**
 * Copyright (C) 2010-2011 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX.  If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx.hooks.events;

import org.pircbotx.User;
import org.pircbotx.hooks.Event;
import org.pircbotx.HeufyBot;
/**
 * Called when the mode of a user is set.
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */

public class UserModeEvent<T extends HeufyBot> extends Event<T> {
	protected final User target;
	protected final User source;
	protected final String mode;
	/**
	 * Default constructor to setup object. Timestamp is automatically set
	 * to current time as reported by {@link System#currentTimeMillis() }
	 * @param target The user that the mode operation applies to.
	 * @param source The user that set the mode.
	 * @param mode The mode that has been set.
	 */
	public UserModeEvent(T bot, User target, User source, String mode) {
		super(bot);
		this.target = target;
		this.source = source;
		this.mode = mode;
	}
	/**
	 * Respond with a private message to the source user
	 * @param response The response to send 
	 */
	@Override
	public void respond(String response) {
		getBot().sendMessage(getSource(), response);
	}
	
	@java.lang.SuppressWarnings("all")
	public User getTarget() {
		return this.target;
	}
	
	@java.lang.SuppressWarnings("all")
	public User getSource() {
		return this.source;
	}
	
	@java.lang.SuppressWarnings("all")
	public String getMode() {
		return this.mode;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public java.lang.String toString() {
		return "UserModeEvent(target=" + this.getTarget() + ", source=" + this.getSource() + ", mode=" + this.getMode() + ")";
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof UserModeEvent)) return false;
		final UserModeEvent<?> other = (UserModeEvent<?>)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		if (this.getTarget() == null ? other.getTarget() != null : !this.getTarget().equals((java.lang.Object)other.getTarget())) return false;
		if (this.getSource() == null ? other.getSource() != null : !this.getSource().equals((java.lang.Object)other.getSource())) return false;
		if (this.getMode() == null ? other.getMode() != null : !this.getMode().equals((java.lang.Object)other.getMode())) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof UserModeEvent;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + super.hashCode();
		result = result * PRIME + (this.getTarget() == null ? 0 : this.getTarget().hashCode());
		result = result * PRIME + (this.getSource() == null ? 0 : this.getSource().hashCode());
		result = result * PRIME + (this.getMode() == null ? 0 : this.getMode().hashCode());
		return result;
	}
}