// Generated by delombok at Fri May 17 11:49:19 CEST 2013
/**
 * Copyright (C) 2010-2013 Leon Blakey <lord.quackstar at gmail.com>
 *
 * This file is part of PircBotX.
 *
 * PircBotX is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PircBotX is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PircBotX. If not, see <http://www.gnu.org/licenses/>.
 */
package org.pircbotx.hooks.events;

import java.util.Collections;
import java.util.List;
import org.pircbotx.HeufyBot;
import org.pircbotx.hooks.Event;
/**
 * Dispatched when we receive a completed Whois request. Note this is completely
 * independent of User and Channel objects since a user might not be connected to
 * us directly
 * @author Leon Blakey <lord.quackstar at gmail.com>
 */

@SuppressWarnings({"unchecked", "rawtypes"})
public class WhoisEvent<T extends HeufyBot> extends Event<T> {
	protected WhoisEventBuilder builder;
	
	public WhoisEvent(T bot, WhoisEventBuilder builder) {
		super(bot);
		this.builder = builder;
	}
	
	@Override
	public void respond(String response) {
		bot.sendMessage(getNick(), response);
	}
	
	public List<String> getChannels() {
		//Project Lombok doesn't like Delagates with generics
		return builder.getChannels();
	}
	
	public static class WhoisEventBuilder<J extends HeufyBot> {
		protected String nick;
		protected String login;
		protected String hostname;
		protected String realname;
		protected List<String> channels;
		protected String server;
		protected String serverInfo;
		protected long idleSeconds;
		protected long signOnTime;
		protected String registeredAs;
		
		public List<String> getChannels() {
			return Collections.unmodifiableList(channels);
		}
		
		public WhoisEvent generateEvent(J bot) {
			return new WhoisEvent(bot, this);
		}
		
		@java.lang.SuppressWarnings("all")
		public WhoisEventBuilder() {
			
		}
		
		@java.lang.SuppressWarnings("all")
		public String getNick() {
			return this.nick;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getLogin() {
			return this.login;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getHostname() {
			return this.hostname;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getRealname() {
			return this.realname;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getServer() {
			return this.server;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getServerInfo() {
			return this.serverInfo;
		}
		
		@java.lang.SuppressWarnings("all")
		public long getIdleSeconds() {
			return this.idleSeconds;
		}
		
		@java.lang.SuppressWarnings("all")
		public long getSignOnTime() {
			return this.signOnTime;
		}
		
		@java.lang.SuppressWarnings("all")
		public String getRegisteredAs() {
			return this.registeredAs;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setNick(final String nick) {
			this.nick = nick;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setLogin(final String login) {
			this.login = login;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setHostname(final String hostname) {
			this.hostname = hostname;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setRealname(final String realname) {
			this.realname = realname;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setChannels(final List<String> channels) {
			this.channels = channels;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setServer(final String server) {
			this.server = server;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setServerInfo(final String serverInfo) {
			this.serverInfo = serverInfo;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setIdleSeconds(final long idleSeconds) {
			this.idleSeconds = idleSeconds;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setSignOnTime(final long signOnTime) {
			this.signOnTime = signOnTime;
		}
		
		@java.lang.SuppressWarnings("all")
		public void setRegisteredAs(final String registeredAs) {
			this.registeredAs = registeredAs;
		}
		
		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public boolean equals(final java.lang.Object o) {
			if (o == this) return true;
			if (!(o instanceof WhoisEvent.WhoisEventBuilder)) return false;
			final WhoisEventBuilder<?> other = (WhoisEventBuilder<?>)o;
			if (!other.canEqual((java.lang.Object)this)) return false;
			final java.lang.Object this$nick = this.getNick();
			final java.lang.Object other$nick = other.getNick();
			if (this$nick == null ? other$nick != null : !this$nick.equals(other$nick)) return false;
			final java.lang.Object this$login = this.getLogin();
			final java.lang.Object other$login = other.getLogin();
			if (this$login == null ? other$login != null : !this$login.equals(other$login)) return false;
			final java.lang.Object this$hostname = this.getHostname();
			final java.lang.Object other$hostname = other.getHostname();
			if (this$hostname == null ? other$hostname != null : !this$hostname.equals(other$hostname)) return false;
			final java.lang.Object this$realname = this.getRealname();
			final java.lang.Object other$realname = other.getRealname();
			if (this$realname == null ? other$realname != null : !this$realname.equals(other$realname)) return false;
			final java.lang.Object this$channels = this.getChannels();
			final java.lang.Object other$channels = other.getChannels();
			if (this$channels == null ? other$channels != null : !this$channels.equals(other$channels)) return false;
			final java.lang.Object this$server = this.getServer();
			final java.lang.Object other$server = other.getServer();
			if (this$server == null ? other$server != null : !this$server.equals(other$server)) return false;
			final java.lang.Object this$serverInfo = this.getServerInfo();
			final java.lang.Object other$serverInfo = other.getServerInfo();
			if (this$serverInfo == null ? other$serverInfo != null : !this$serverInfo.equals(other$serverInfo)) return false;
			if (this.getIdleSeconds() != other.getIdleSeconds()) return false;
			if (this.getSignOnTime() != other.getSignOnTime()) return false;
			final java.lang.Object this$registeredAs = this.getRegisteredAs();
			final java.lang.Object other$registeredAs = other.getRegisteredAs();
			if (this$registeredAs == null ? other$registeredAs != null : !this$registeredAs.equals(other$registeredAs)) return false;
			return true;
		}
		
		@java.lang.SuppressWarnings("all")
		public boolean canEqual(final java.lang.Object other) {
			return other instanceof WhoisEvent.WhoisEventBuilder;
		}
		
		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public int hashCode() {
			final int PRIME = 31;
			int result = 1;
			final java.lang.Object $nick = this.getNick();
			result = result * PRIME + ($nick == null ? 0 : $nick.hashCode());
			final java.lang.Object $login = this.getLogin();
			result = result * PRIME + ($login == null ? 0 : $login.hashCode());
			final java.lang.Object $hostname = this.getHostname();
			result = result * PRIME + ($hostname == null ? 0 : $hostname.hashCode());
			final java.lang.Object $realname = this.getRealname();
			result = result * PRIME + ($realname == null ? 0 : $realname.hashCode());
			final java.lang.Object $channels = this.getChannels();
			result = result * PRIME + ($channels == null ? 0 : $channels.hashCode());
			final java.lang.Object $server = this.getServer();
			result = result * PRIME + ($server == null ? 0 : $server.hashCode());
			final java.lang.Object $serverInfo = this.getServerInfo();
			result = result * PRIME + ($serverInfo == null ? 0 : $serverInfo.hashCode());
			final long $idleSeconds = this.getIdleSeconds();
			result = result * PRIME + (int)($idleSeconds >>> 32 ^ $idleSeconds);
			final long $signOnTime = this.getSignOnTime();
			result = result * PRIME + (int)($signOnTime >>> 32 ^ $signOnTime);
			final java.lang.Object $registeredAs = this.getRegisteredAs();
			result = result * PRIME + ($registeredAs == null ? 0 : $registeredAs.hashCode());
			return result;
		}
		
		@java.lang.Override
		@java.lang.SuppressWarnings("all")
		public java.lang.String toString() {
			return "WhoisEvent.WhoisEventBuilder(nick=" + this.getNick() + ", login=" + this.getLogin() + ", hostname=" + this.getHostname() + ", realname=" + this.getRealname() + ", channels=" + this.getChannels() + ", server=" + this.getServer() + ", serverInfo=" + this.getServerInfo() + ", idleSeconds=" + this.getIdleSeconds() + ", signOnTime=" + this.getSignOnTime() + ", registeredAs=" + this.getRegisteredAs() + ")";
		}
	}
	
	protected static interface WhoisEventBuilderIncludes {
		
		String getNick();
		
		String getLogin();
		
		String getHostname();
		
		String getRealname();
		
		String getServer();
		
		String getServerInfo();
		
		long getIdleSeconds();
		
		long getSignOnTime();
		
		String getRegisteredAs();
		
		@Override
		String toString();
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public boolean equals(final java.lang.Object o) {
		if (o == this) return true;
		if (!(o instanceof WhoisEvent)) return false;
		final WhoisEvent<?> other = (WhoisEvent<?>)o;
		if (!other.canEqual((java.lang.Object)this)) return false;
		if (!super.equals(o)) return false;
		final java.lang.Object this$builder = this.builder;
		final java.lang.Object other$builder = other.builder;
		if (this$builder == null ? other$builder != null : !this$builder.equals(other$builder)) return false;
		return true;
	}
	
	@java.lang.SuppressWarnings("all")
	public boolean canEqual(final java.lang.Object other) {
		return other instanceof WhoisEvent;
	}
	
	@java.lang.Override
	@java.lang.SuppressWarnings("all")
	public int hashCode() {
		final int PRIME = 31;
		int result = 1;
		result = result * PRIME + super.hashCode();
		final java.lang.Object $builder = this.builder;
		result = result * PRIME + ($builder == null ? 0 : $builder.hashCode());
		return result;
	}
	
	@java.lang.SuppressWarnings("all")
	public java.lang.String getNick() {
		return this.builder.getNick();
	}
	
	@java.lang.SuppressWarnings("all")
	public java.lang.String getLogin() {
		return this.builder.getLogin();
	}
	
	@java.lang.SuppressWarnings("all")
	public java.lang.String getHostname() {
		return this.builder.getHostname();
	}
	
	@java.lang.SuppressWarnings("all")
	public java.lang.String getRealname() {
		return this.builder.getRealname();
	}
	
	@java.lang.SuppressWarnings("all")
	public java.lang.String getServer() {
		return this.builder.getServer();
	}
	
	@java.lang.SuppressWarnings("all")
	public java.lang.String getServerInfo() {
		return this.builder.getServerInfo();
	}
	
	@java.lang.SuppressWarnings("all")
	public long getIdleSeconds() {
		return this.builder.getIdleSeconds();
	}
	
	@java.lang.SuppressWarnings("all")
	public long getSignOnTime() {
		return this.builder.getSignOnTime();
	}
	
	@java.lang.SuppressWarnings("all")
	public java.lang.String getRegisteredAs() {
		return this.builder.getRegisteredAs();
	}
}